### ISSUE TITLE
Build Spring Boot application for collecting sensor values

### ISSUE THREAD

**Issue by wernerfragner** [wernerfragner/oekofen-stats#1]
**Goal**: Build a Spring Boot application *oekofen-collector* that collects all sensor values in a configurable interval and that writes the values as JSON to InfluxDB.

Constraints: provide plugin-mechanism for misc. collection targets.

Configuration Options:
```
 collect:
  interval-seconds: 60
  source:
    host: 127.0.0.1
    port: 4321
    password: somepass
  target:
    influxdb:
      url: http://127.0.0.1:8086
      token: <api-token>
      organization: my-org
      bucket: my-bucket
```
