### ISSUE TITLE
Add logic to import existing CSV data

### ISSUE THREAD

**Issue by wernerfragner** [wernerfragner/oekofen-stats#7]
Implement a second source (beside the JSON API source) that imports data from given a CSV files directory. It is intended for one-time-imports - not for continuous imports with change detection.

**Constraints**

- No change detection is implemented.
- No duplicate detection is implemented.

**Configuration**
```
collect:
  csv-source: 
    directory: "c:/temp/csv-data"
    separator: ";"
  json-api-source:
    ...
```
